run:
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: false
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: false
linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/org/project
  revive:
    min-confidence: 0.8
  govet:
    check-shadowing: true
    settings:
      printf: 
        funcs: 
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    enable:
      - asmdecl
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - framepointer
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - revive
      - shift
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    enable-all: false
    disable:
      - shadow
    disable-all: false

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - gosec
  disable:
    - scopelint
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false


issues:
  exclude-use-default: false
  exclude-case-sensitive: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true

severity:
  default-severity: error
  case-sensitive: false
