context: chaordic # project in GCP terms
region: europe-west6
resources:
  cloudrun:
  - name: cloudrun-srv
    domain:
      name: cde.app 
      dns_zone: cdeapp 
    memory: 512Mi
    cpu: 1
    timeout: 300
    max_requests: 80
    scaling:
      min_instances: 0
      max_instances: 100
  cloudsql:
  - name: my-pg-db 
    machine_type: db-f1-micro 
    storage_size: 10
  vpc_access_connector:
    min_instances: 2
    max_instances: 3
    instance_type: e2-standard-4
