name: cloudrun-srv
runtime: cloudrun
spec:
  base_name: hello-app
  http:
    public: true
    http2: false
depends_on:
  cloudsql: 
  - name: my-pg-db
    type: postgres
  pubsub:
    consume:
    - name: some_topic
    - name: some_other_topic
      owner: true
    produce:
    - name: third_type_of_topic
  cloudstorage:
  - name: foo-bucket
    access: read
  - name: bar
    access: read
    owner: true
  - name: baz
    public: true
    access: readwrite
  cloudrun:
  - name: cloudrun-srv2
    env: SRV2
env:
  vars:
    foo: bar

