name: dev
dynamic: true
project:  chaordic-dev
region: europe-west6
deployment:
  trigger:
    is_local: true
    git:
      branch: feature/**
      event: commit
env:
  vars:
    foo: baz
  secrets:
    verySecret: 
      name: very-secret-dev
      type: volume # env